In [1]:
import pandas as pd
import numpy as np

print("pandas:", pd.__version__)
print("numpy:", np.__version__)

pandas: 3.0.5
numpy: 2.5.1

In [2]:
df = pd.DataFrame({
    "name": ["A", "B", "C", "C", "D"],
    "age": [20, 21, 22, 22, 200],
    "score": [88, 92, 76, 76, 95],
    "date": [
        "2026-08-01",
        "2026-08-02",
        "2026-08-03",
        "2026-08-03",
        "2026-08-05"
    ],
    "height_cm": [170, 175, 168, 168, 180]
})

# 再故意制造一个缺失值
df.loc[1, "score"] = np.nan

df

  name  age  score        date  height_cm
0    A   20   88.0  2026-08-01        170
1    B   21    NaN  2026-08-02        175
2    C   22   76.0  2026-08-03        168
3    C   22   76.0  2026-08-03        168
4    D  200   95.0  2026-08-05        180

In [3]:
print("数据规模：", df.shape)

print("\n列名：")
print(df.columns)

print("\n数据类型：")
print(df.dtypes)

print("\n前5行：")
print(df.head())

print("\n基本信息：")
df.info()

print("\n数据统计：")
df.describe()

数据规模： (5, 5)

列名：
Index(['name', 'age', 'score', 'date', 'height_cm'], dtype='str')

数据类型：
name             str
age            int64
score        float64
date             str
height_cm      int64
dtype: object

前5行：
  name  age  score        date  height_cm
0    A   20   88.0  2026-08-01        170
1    B   21    NaN  2026-08-02        175
2    C   22   76.0  2026-08-03        168
3    C   22   76.0  2026-08-03        168
4    D  200   95.0  2026-08-05        180

基本信息：
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       5 non-null      str
 1   age        5 non-null      int64
 2   score      4 non-null      float64
 3   date       5 non-null      str
 4   height_cm  5 non-null      int64
dtypes: float64(1), int64(2), str(2)
memory usage: 332.0 bytes

数据统计：

             age      score   height_cm
count    5.00000   4.000000    5.000000
mean    57.00000  83.750000  172.200000
std     79.94373   9.394147    5.215362
min     20.00000  76.000000  168.000000
25%     21.00000  76.000000  168.000000
50%     22.00000  82.000000  170.000000
75%     22.00000  89.750000  175.000000
max    200.00000  95.000000  180.000000

In [4]:
print("每列缺失值统计:\n",df.isna().sum())

print("每行重复值统计：\n", df.duplicated().sum())

每列缺失值统计:
 name         0
age          0
score        1
date         0
height_cm    0
dtype: int64
每行重复值统计：
 1

In [5]:
df_clean = df.drop_duplicates()

df_clean

  name  age  score        date  height_cm
0    A   20   88.0  2026-08-01        170
1    B   21    NaN  2026-08-02        175
2    C   22   76.0  2026-08-03        168
4    D  200   95.0  2026-08-05        180

In [6]:
df_clean = df_clean.copy()

score_median = df_clean["score"].median()
print(score_median)

df_clean["score"] = df_clean["score"].fillna(score_median)

df_clean

88.0

  name  age  score        date  height_cm
0    A   20   88.0  2026-08-01        170
1    B   21   88.0  2026-08-02        175
2    C   22   76.0  2026-08-03        168
4    D  200   95.0  2026-08-05        180

当一个 DataFrame 是从另一个 DataFrame 筛选出来时，Pandas 有时不知道你修改的是：原数据的一部分，还是一个独立副本。加上copy()可以避免歧义

In [7]:
df_clean["age"].between(0,120)

df_clean.loc[~df_clean["age"].between(0,120), "age"] = np.nan

df_clean

age_median = df_clean["age"].median()
df_clean["age"] = df_clean["age"].fillna(age_median)

df_clean

  name   age  score        date  height_cm
0    A  20.0   88.0  2026-08-01        170
1    B  21.0   88.0  2026-08-02        175
2    C  22.0   76.0  2026-08-03        168
4    D  21.0   95.0  2026-08-05        180

In [8]:
print(df_clean)

print("\n缺失值：")
print(df_clean.isna().sum())

print("\n描述统计：")
print(df_clean.describe())

  name   age  score        date  height_cm
0    A  20.0   88.0  2026-08-01        170
1    B  21.0   88.0  2026-08-02        175
2    C  22.0   76.0  2026-08-03        168
4    D  21.0   95.0  2026-08-05        180

缺失值：
name         0
age          0
score        0
date         0
height_cm    0
dtype: int64

描述统计：
             age      score   height_cm
count   4.000000   4.000000    4.000000
mean   21.000000  86.750000  173.250000
std     0.816497   7.889867    5.377422
min    20.000000  76.000000  168.000000
25%    20.750000  85.000000  169.500000
50%    21.000000  88.000000  172.500000
75%    21.250000  89.750000  176.250000
max    22.000000  95.000000  180.000000

In [9]:
# 将字符串转化为实际的日期
df_clean.dtypes

df_clean["date"] = pd.to_datetime(df_clean["date"])

df_clean.dtypes

df_clean["day"] = df_clean["date"].dt.day

df_clean

  name   age  score       date  height_cm  day
0    A  20.0   88.0 2026-08-01        170    1
1    B  21.0   88.0 2026-08-02        175    2
2    C  22.0   76.0 2026-08-03        168    3
4    D  21.0   95.0 2026-08-05        180    5

In [10]:
# 数据筛选
df_clean[df_clean["score"] > 85]

  name   age  score       date  height_cm  day
0    A  20.0   88.0 2026-08-01        170    1
1    B  21.0   88.0 2026-08-02        175    2
4    D  21.0   95.0 2026-08-05        180    5

In [11]:
# groupby
df_clean["group"] = ["A", "A", "B", "B"]

df_clean.groupby(by="group", as_index=False)[["score", "age"]].mean()

df_clean.groupby("group")["score"].agg(["mean", "max", "min", "median"])

       mean   max   min  median
group
A      88.0  88.0  88.0    88.0
B      85.5  95.0  76.0    85.5

In [12]:
# merge：把两张表拼起来
df_extra = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "city": ["Beijing", "Shanghai", "Harbin", "Hangzhou"]
})

df_extra

df_merged = pd.merge(left=df_clean, right=df_extra, on="name",how="left")

df_merged

  name   age  score       date  height_cm  day group      city
0    A  20.0   88.0 2026-08-01        170    1     A   Beijing
1    B  21.0   88.0 2026-08-02        175    2     A  Shanghai
2    C  22.0   76.0 2026-08-03        168    3     B    Harbin
3    D  21.0   95.0 2026-08-05        180    5     B  Hangzhou

In [13]:
# pivot_table：做透视表
df_clean["gender"] = ["M", "F", "M", "F"]

df_clean.pivot_table(values="score", index="group", columns="gender", aggfunc="mean")

gender     F     M
group
A       88.0  88.0
B       95.0  76.0

In [14]:
# 练习
df_clean["group"] = ["A", "A", "B", "B"]
# 1. date 转 datetime
df_clean["date"] = pd.to_datetime(df_clean["date"])
df_clean.dtypes

# 2. 筛选 score >= 85 的记录
df_clean[df_clean["score"] >= 85]

# 3. 按 group 求 score 平均值
df_clean.groupby(by="group", as_index=True)["score"].mean()

# 4. 按 group 求 score 的 mean/max/min
df_clean.groupby(by="group", as_index=True)["score"].agg(["mean", "max", "min"])

# 5. 创建 df_extra，并按 name merge
df_extra = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "city": ["Beijing", "Shanghai", "Harbin", "Hangzhou"]
})
df_merged = pd.merge(df_clean, df_extra, how="left", on="name")

# 6. 用 pivot_table 求每组平均 score
df_merged.pivot_table(values="score", index="group", aggfunc="mean")

       score
group
A       88.0
B       85.5

In [19]:
from src.datareport import data_check

raw_report, raw_duplicates = data_check(df)
clean_report, clean_duplicates = data_check(df_clean)

print("===== 原始数据 =====")
display(raw_report)
print("重复行数：", raw_duplicates)

print("\n===== 清洗后数据 =====")
display(clean_report)
print("重复行数：", clean_duplicates)

===== 原始数据 =====

,dtype,missing_count,missing_rate,unique_count,mean,std,min,max
name,str,0,0.0,4,NaN,NaN,NaN,NaN
age,int64,0,0.0,4,57.00,79.943730,20.0,200.0
score,float64,1,0.2,3,83.75,9.394147,76.0,95.0
date,str,0,0.0,4,NaN,NaN,NaN,NaN
height_cm,int64,0,0.0,4,172.20,5.215362,168.0,180.0

重复行数： 1

===== 清洗后数据 =====

,dtype,missing_count,missing_rate,unique_count,mean,std,min,max
name,str,0,0.0,4,NaN,NaN,NaN,NaN
age,float64,0,0.0,3,21.00,0.816497,20.0,22.0
score,float64,0,0.0,3,86.75,7.889867,76.0,95.0
date,datetime64[us],0,0.0,4,NaN,NaN,NaN,NaN
height_cm,int64,0,0.0,4,173.25,5.377422,168.0,180.0
day,int32,0,0.0,4,2.75,1.707825,1.0,5.0
group,str,0,0.0,2,NaN,NaN,NaN,NaN
gender,str,0,0.0,2,NaN,NaN,NaN,NaN

重复行数： 0

In [20]:
df_clean.to_excel("outputs/processed_data.xlsx", index=False)

raw_report.to_csv("outputs/data_report_clean.csv", encoding="utf-8-sig")

In [21]:
cleaning_log = pd.DataFrame({
    "column": [
        "name",
        "age",
        "score",
        "date",
        "height_cm"
    ],
    "operation": [
        "删除重复记录",
        "异常值200设为缺失后使用中位数填充",
        "缺失值使用中位数填充",
        "转换为datetime类型",
        "无处理"
    ]
})

cleaning_log

      column           operation
0       name              删除重复记录
1        age  异常值200设为缺失后使用中位数填充
2      score          缺失值使用中位数填充
3       date       转换为datetime类型
4  height_cm                 无处理

In [22]:
cleaning_log.to_csv(
    "outputs/cleaning_log.csv",
    index=False,
    encoding="utf-8-sig"
)

In [23]:
print(df.shape)
print(df_clean.shape)

print(df_clean.isna().sum())
print(df_clean.duplicated().sum())

(5, 5)
(4, 8)
name         0
age          0
score        0
date         0
height_cm    0
day          0
group        0
gender       0
dtype: int64
0